services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-challenge-api
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: tech-challenge-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fastfood
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
